### ISSUE TITLE
Remediate all instances of "Missing Title" labels in ArchivesSpace

### ISSUE THREAD

**Issue by fordmadox** [Smithsonian/caas-aspace-scripts#1]
Arrangement notes having "Missing Title" as the first item in a bulleted list. Want to remove that item from the list and bump everything up.

Search "Missing Title" in sova. 

Mark, to do:  link an SQL export of all instances of this, so that we don't have to do Solr API searches as part of this process.

**Comment by crugas** [comment]
@fordmadox To get @crugas csv of all resources/archival object URIs with missing titles.

**Comment by fordmadox** [comment]
5 units to contact:



![Image](https://github.com/user-attachments/assets/4302e203-2ba0-4b66-9119-8f04b3750902)

**Comment by fordmadox** [comment]
Mark to do:  provide email contacts for the 5 repositories, once we've made the changes in TEST so that Corey and email each to discuss next steps for PROD ASpace.

(also figure out how GitHub converted by copy and paste of text to an image!).

**Comment by fordmadox** [comment]
Email contacts for each unit, so that you can reach out directly once I've run these updates in ASpace TEST:

AAA:  Erin Kinhart <KinhartE@si.edu>
CFCH: Cecilia Peterson <PetersonC@si.edu> 
NAA: Gina Rappaport <RappaportG@si.edu>
NASM: Jessamyn Lloyd <LloydJN@si.edu>
NMAH-AC:  Alison Oswald <oswalda@si.edu>

There are more folks from each of those repositories who we will meet with when we do the rounds, but for this data update, I'd just start with each of the above archivists when we're ready to reach out.

**Comment by crugas** [comment]
> Email contacts for each unit, so that you can reach out directly once I've run these updates in ASpace TEST:
> 
> AAA: Erin Kinhart [KinhartE@si.edu](mailto:KinhartE@si.edu) CFCH: Cecilia Peterson [PetersonC@si.edu](mailto:PetersonC@si.edu) NAA: Gina Rappaport [RappaportG@si.edu](mailto:RappaportG@si.edu) NASM: Jessamyn Lloyd [LloydJN@si.edu](mailto:LloydJN@si.edu) NMAH-AC: Alison Oswald [oswalda@si.edu](mailto:oswalda@si.edu)
> 
> There are more folks from each of those repositories who we will meet with when we do the rounds, but for this data update, I'd just start with each of the above archivists when we're ready to reach out.

@fordmadox I'll draft up an email and send it to you for review before I send it to everyone on the list.

**Comment by crugas** [comment]
> Email contacts for each unit, so that you can reach out directly once I've run these updates in ASpace TEST:
> 
> AAA: Erin Kinhart [KinhartE@si.edu](mailto:KinhartE@si.edu) CFCH: Cecilia Peterson [PetersonC@si.edu](mailto:PetersonC@si.edu) NAA: Gina Rappaport [RappaportG@si.edu](mailto:RappaportG@si.edu) NASM: Jessamyn Lloyd [LloydJN@si.edu](mailto:LloydJN@si.edu) NMAH-AC: Alison Oswald [oswalda@si.edu](mailto:oswalda@si.edu)
> 
> There are more folks from each of those repositories who we will meet with when we do the rounds, but for this data update, I'd just start with each of the above archivists when we're ready to reach out.

Emails sent this morning to above listed individuals with review date of next Friday, August 15.

**Comment by crugas** [comment]
Update performed on ASpace prod 19/08/24. @fordmadox Ok to close this issue?
