### ISSUE TITLE
Update old-style MADS links to current-style MADS links

### ISSUE THREAD

**Issue by fordmadox** [Smithsonian/caas-aspace-scripts#12]
Existing values include (where the capital letters represent variables):

edu/media/UNIT/UAN.mp3
edu/media/UAN.mp3
edu/media/UNIT/UAN.pdf
edu/media/UAN.pdf

In all cases, the "mp3" audio assets should be updated to:

https://mads.si.edu/mads/view/UAN

And the "pdf" assets should be updated to:

https://mads.si.edu/mads/id/UAN

**Comment by fordmadox** [comment]
For input file, see:  https://sinet.sharepoint.com/:x:/r/sites/OCIO-DigitalPlatforms-CAASB/Shared%20Documents/Data%20Cleanup%20Projects/ArchivesSpace/[NotStandardLink_daos.xlsx](https://sinet.sharepoint.com/:x:/r/sites/OCIO-DigitalPlatforms-CAASB/Shared%20Documents/Data%20Cleanup%20Projects/ArchivesSpace/NotStandardLink_daos.xlsx?d=wde53e411ebf9434db42f81a78c245461&csf=1&web=1&e=SsEb4b)?d=wde53e411ebf9434db42f81a78c245461&csf=1&web=1&e=SsEb4b

Will also share one sample SQL query that can be used if desired.

**Comment by lorawoodford** [comment]
Completed 12/17.  86 pdf links following this pattern still need to be updated: https://sinet-my.sharepoint.com/:x:/r/personal/woodfordlj_si_edu/Documents/20241217_mads_pdf_update_errors.xlsx?d=w5ed7382f73ca461589b6db47138e4b85&csf=1&web=1&e=cIRO6t
