### ISSUE TITLE
Work with CFCH to migrate CFCH.GUIA from TEST to PROD ASpace...

### ISSUE THREAD

**Issue by crugas** [Smithsonian/caas-aspace-scripts#2]
...also take the time to go over a bit of training regarding ASpace after reviewing the data.

**Comment by fordmadox** [comment]
File uploaded, and subjects fixed.  See https://aspace.si.edu/resources/54853

Next step:  @fordmadox to schedule a meeting with CFHC the week of August 5th.

**Comment by fordmadox** [comment]
File shared with the unit.  No meeting scheduled for next week (it's a busy week!), but we will proceed with one if requested by the unit.

If the request comes up again, we can further refine the process of moving a test file over to prod, but this should generally be discouraged.
