### ISSUE TITLE
Remove duplicate data from digital object records

### ISSUE THREAD

**Issue by crugas** [Smithsonian/caas-aspace-scripts#5]
See NMAH, etc.

Once done, close out https://jira-telework.si.edu/browse/SIRISSOVA-1033

**Comment by crugas** [comment]
@fordmadox To get an SQL query based on digital objects that have notes - CSV to @crugas

**Comment by crugas** [comment]
@crugas 
TODO: review Dates specifically to make sure none of them a digitized. If label == digitized.
TODO: build in saving the ORIGINAL digital object JSON metadata in a separate file - just in case we delete data we needed to keep

**Comment by fordmadox** [comment]
Not build for speed, but built for readability (since I'm not great at SQL), but check out: https://github.com/Smithsonian/caas-aspace-scripts/blob/issue_5/sql_scripts/delte_dometadata_query_union_example.sql

**Comment by crugas** [comment]
@fordmadox So that's how to use Unions! Thank you for sharing that! When I ran the query above, it returned 32,688 digital objects. It's 159 digital objects more than our original pass of 32.529, so I'm curious how it's getting those extra digital objects and what they are.

**Comment by lorawoodford** [comment]
@crugas Unrelated, but interestingly that solr search I shared also returns 32,688.  That confirms the search is good, at least.

**Comment by crugas** [comment]
UPDATE:

AAA: For the 29, those were most likely deleted in the most current PROD instance. They are in the process of deleting old digital objects and replacing them with new ones using the CDIS process. So this should be ok!

AAG: There is a volunteer adding dates data to their digital objects currently, which explains why there is a discrepancy with more digital objects compared to the log and JSON file.

Also, TIL that ASpace's repo 1 is actually the global repository for storing controlled vocabs, subjects, agents, etc.. so anything that's global to all repos. That's why starting repositories in an ASpace instance always start with 2, not 1.

**Comment by fordmadox** [comment]
@crugas :  okay to close this one out?

**Comment by crugas** [comment]
@fordmadox Yes! Successfully ran the report on November 25 at 4 PM EST.
